vim.keymap.set('n', '<leader>gs', '<cmd>Git<CR>')
vim.keymap.set('n', '<leader>gd', '<cmd>Gvdiffsplit<CR>')
vim.keymap.set('n', '<leader>gb', '<cmd>Git blame<CR>')
vim.keymap.set('n', '<leader>gc', '<cmd>Git add . | Git commit<CR>')
vim.keymap.set('n', '<leader><C-g>p', '<cmd>Git push<CR>')
