require('plugins-config.lsp')
require('plugins-config.treesitter')
require('plugins-config.colors')
require('plugins-config.discord')
require('plugins-config.luasnip')
require('plugins-config.prettier')
require('plugins-config.startup')
require('plugins-config.fold')
