require('plugins-config/lsp')
require('plugins-config/treesitter')
require('plugins-config/colors')
require('plugins-config/airline')
require('plugins-config/discord')
require('plugins-config/luasnip')
require('plugins-config/prettier')
