require('plugins-config.luasnip')
require('plugins-config.lsp')
-- require('plugins-config.treesitter')
require('plugins-config.fold')
require('plugins-config.colors')
require('plugins-config.discord')
--require('plugins-config.prettier')
require('plugins-config.startup')
--require('plugins-config.error-lens')
require('plugins-config.harpoon')
